/* ═══════════════════════════════════════════
   KSN AAHAAR — Constants & Menu Data
   ═══════════════════════════════════════════ */

import type { Product, Category } from '@/types';

// ── Brand ──
export const BRAND = {
  name: 'KSN AAHAAR',
  tagline: 'Taste the Warmth of Home, Delivered Fresh',
  description: 'Authentic flavours, lovingly prepared and delivered fresh from KSN AAHAAR.',
  location: 'Miyapur, Hyderabad, Telangana, India',
  phone: '+91 98765 43210',
  email: 'order@ksnaahaar.com',
  whatsapp: '+91 98765 43210',
} as const;

// ── API ──
export const API_BASE_URL = process.env.NEXT_PUBLIC_API_URL || 'http://localhost:5000/api';

// ── Delivery Defaults ──
export const DELIVERY_DEFAULTS = {
  charge: 30,
  freeThreshold: 500,
  minOrder: 199,
  estimatedTime: '30-45 min',
} as const;

// ── Categories ──
export const CATEGORIES: Category[] = [
  {
    id: 'cat-biriyanis',
    name: 'Biriyanis',
    slug: 'biriyanis',
    description: 'Aromatic rice dishes slow-cooked with traditional spices',
    image: '/images/food/biriyani-category.jpg',
    displayOrder: 1,
    itemCount: 10,
  },
  {
    id: 'cat-rice-items',
    name: 'Rice Items',
    slug: 'rice-items',
    description: 'Traditional rice preparations made with authentic flavours',
    image: '/images/food/rice-category.jpg',
    displayOrder: 2,
    itemCount: 6,
  },
  {
    id: 'cat-nonveg-curries',
    name: 'Non-Veg Curries',
    slug: 'non-veg-curries',
    description: 'Rich curries and fries prepared with fresh meat and spices',
    image: '/images/food/nonveg-curry-category.jpg',
    displayOrder: 3,
    itemCount: 6,
  },
  {
    id: 'cat-veg-curries',
    name: 'Veg Curries',
    slug: 'veg-curries',
    description: 'Comforting vegetarian curries from traditional recipes',
    image: '/images/food/veg-curry-category.jpg',
    displayOrder: 4,
    itemCount: 7,
  },
  {
    id: 'cat-sweets',
    name: 'Sweets',
    slug: 'sweets',
    description: 'Traditional Indian sweets made with love and premium ingredients',
    image: '/images/food/sweets-category.jpg',
    displayOrder: 5,
    itemCount: 8,
  },
  {
    id: 'cat-snacks-sweet',
    name: 'Snacks — Sweet',
    slug: 'snacks-sweet',
    description: 'Handmade sweet snacks and laddus for celebrations',
    image: '/images/food/sweet-snacks-category.jpg',
    displayOrder: 6,
    itemCount: 9,
  },
  {
    id: 'cat-snacks-hot',
    name: 'Snacks — Hot',
    slug: 'snacks-hot',
    description: 'Crunchy and spicy traditional savoury snacks',
    image: '/images/food/hot-snacks-category.jpg',
    displayOrder: 7,
    itemCount: 7,
  },
];

// ── Helper to generate slug ──
function slugify(text: string): string {
  return text.toLowerCase().replace(/[^a-z0-9]+/g, '-').replace(/(^-|-$)/g, '');
}

// ── Full Menu Data ──
export const PRODUCTS: Product[] = [
  // ═══ BIRIYANIS ═══
  {
    id: 'prod-001',
    name: 'Chicken Dum Biriyani',
    slug: 'chicken-dum-biriyani',
    description: 'Aromatic basmati rice layered with tender chicken and traditional spices, slow-cooked to bring out rich, authentic flavour.',
    shortDescription: 'Aromatic basmati rice with tender chicken, slow-cooked with traditional spices.',
    category: 'Biriyanis',
    categorySlug: 'biriyanis',
    image: '/images/food/chicken-dum-biriyani.jpg',
    isVeg: false,
    isAvailable: true,
    isFeatured: true,
    variants: [
      { id: 'v-001-s', name: 'Single', price: 299, isAvailable: true },
      { id: 'v-001-f', name: 'Family Pack', price: 799, isAvailable: true },
    ],
    ingredients: ['Basmati Rice', 'Chicken', 'Yogurt', 'Onions', 'Mint', 'Saffron', 'Traditional Spices'],
    servingInfo: 'Single serves 1, Family Pack serves 3-4',
    displayOrder: 1,
    popularity: 100,
  },
  {
    id: 'prod-002',
    name: 'Chicken Fry Biriyani',
    slug: 'chicken-fry-biriyani',
    description: 'Fragrant basmati rice layered with crispy fried chicken pieces, infused with aromatic spices and cooked to perfection.',
    shortDescription: 'Fragrant basmati rice with crispy fried chicken pieces and aromatic spices.',
    category: 'Biriyanis',
    categorySlug: 'biriyanis',
    image: '/images/food/chicken-fry-biriyani.jpg',
    isVeg: false,
    isAvailable: true,
    isFeatured: true,
    variants: [
      { id: 'v-002-s', name: 'Single', price: 299, isAvailable: true },
      { id: 'v-002-f', name: 'Family Pack', price: 799, isAvailable: true },
    ],
    ingredients: ['Basmati Rice', 'Chicken', 'Onions', 'Green Chillies', 'Mint', 'Traditional Spices'],
    servingInfo: 'Single serves 1, Family Pack serves 3-4',
    displayOrder: 2,
    popularity: 95,
  },
  {
    id: 'prod-003',
    name: 'Mutton Biriyani',
    slug: 'mutton-biriyani',
    description: 'Premium basmati rice slow-cooked with succulent mutton pieces, marinated in rich spices and garnished with fresh herbs.',
    shortDescription: 'Premium basmati rice with succulent mutton, marinated in rich spices.',
    category: 'Biriyanis',
    categorySlug: 'biriyanis',
    image: '/images/food/mutton-biriyani.jpg',
    isVeg: false,
    isAvailable: true,
    isFeatured: true,
    variants: [
      { id: 'v-003-s', name: 'Single', price: 499, isAvailable: true },
      { id: 'v-003-f', name: 'Family Pack', price: 1199, isAvailable: true },
    ],
    ingredients: ['Basmati Rice', 'Mutton', 'Yogurt', 'Onions', 'Saffron', 'Traditional Spices'],
    servingInfo: 'Single serves 1, Family Pack serves 3-4',
    displayOrder: 3,
    popularity: 90,
  },
  {
    id: 'prod-004',
    name: 'Mutton Fry Biriyani',
    slug: 'mutton-fry-biriyani',
    description: 'Aromatic basmati rice paired with perfectly fried mutton pieces, seasoned with a blend of traditional spices.',
    shortDescription: 'Aromatic basmati rice with perfectly fried mutton and traditional spices.',
    category: 'Biriyanis',
    categorySlug: 'biriyanis',
    image: '/images/food/mutton-fry-biriyani.jpg',
    isVeg: false,
    isAvailable: true,
    isFeatured: false,
    variants: [
      { id: 'v-004-s', name: 'Single', price: 499, isAvailable: true },
      { id: 'v-004-f', name: 'Family Pack', price: 1199, isAvailable: true },
    ],
    displayOrder: 4,
    popularity: 85,
  },
  {
    id: 'prod-005',
    name: 'Prawns Biriyani',
    slug: 'prawns-biriyani',
    description: 'Flavourful basmati rice cooked with fresh prawns and a blend of coastal spices, delivering a unique taste of the sea.',
    shortDescription: 'Flavourful basmati rice with fresh prawns and coastal spices.',
    category: 'Biriyanis',
    categorySlug: 'biriyanis',
    image: '/images/food/prawns-biriyani.jpg',
    isVeg: false,
    isAvailable: true,
    isFeatured: true,
    variants: [
      { id: 'v-005-s', name: 'Single', price: 399, isAvailable: true },
      { id: 'v-005-f', name: 'Family Pack', price: 1099, isAvailable: true },
    ],
    displayOrder: 5,
    popularity: 80,
  },
  {
    id: 'prod-006',
    name: 'Mixed Veg Pulao',
    slug: 'mixed-veg-pulao',
    description: 'Basmati rice cooked with a medley of fresh vegetables and mild spices, creating a wholesome and flavourful dish.',
    shortDescription: 'Basmati rice with fresh mixed vegetables and mild spices.',
    category: 'Biriyanis',
    categorySlug: 'biriyanis',
    image: '/images/food/mixed-veg-pulao.jpg',
    isVeg: true,
    isAvailable: true,
    isFeatured: false,
    variants: [
      { id: 'v-006-s', name: 'Single', price: 249, isAvailable: true },
      { id: 'v-006-f', name: 'Family Pack', price: 699, isAvailable: true },
    ],
    displayOrder: 6,
    popularity: 60,
  },
  {
    id: 'prod-007',
    name: 'Veg Pulao',
    slug: 'veg-pulao',
    description: 'Lightly spiced basmati rice with seasonal vegetables, cooked in a traditional style with aromatic whole spices.',
    shortDescription: 'Lightly spiced basmati rice with seasonal vegetables.',
    category: 'Biriyanis',
    categorySlug: 'biriyanis',
    image: '/images/food/veg-pulao.jpg',
    isVeg: true,
    isAvailable: true,
    isFeatured: false,
    variants: [
      { id: 'v-007-s', name: 'Single', price: 199, isAvailable: true },
      { id: 'v-007-f', name: 'Family Pack', price: 499, isAvailable: true },
    ],
    displayOrder: 7,
    popularity: 55,
  },
  {
    id: 'prod-008',
    name: 'Bagara Rice',
    slug: 'bagara-rice',
    description: 'Hyderabadi-style tempered rice with aromatic spices, peanuts, and curry leaves, creating a simple yet flavourful accompaniment.',
    shortDescription: 'Hyderabadi-style tempered rice with peanuts and curry leaves.',
    category: 'Biriyanis',
    categorySlug: 'biriyanis',
    image: '/images/food/bagara-rice.jpg',
    isVeg: true,
    isAvailable: true,
    isFeatured: false,
    variants: [
      { id: 'v-008-s', name: 'Single', price: 199, isAvailable: true },
      { id: 'v-008-f', name: 'Family Pack', price: 499, isAvailable: true },
    ],
    displayOrder: 8,
    popularity: 50,
  },
  {
    id: 'prod-009',
    name: 'Gongura Paneer Biriyani',
    slug: 'gongura-paneer-biriyani',
    description: 'A unique fusion of tangy gongura leaves and soft paneer layered with aromatic basmati rice and Andhra spices.',
    shortDescription: 'Tangy gongura leaves with paneer in aromatic basmati rice.',
    category: 'Biriyanis',
    categorySlug: 'biriyanis',
    image: '/images/food/gongura-paneer-biriyani.jpg',
    isVeg: true,
    isAvailable: true,
    isFeatured: true,
    variants: [
      { id: 'v-009-s', name: 'Single', price: 249, isAvailable: true },
      { id: 'v-009-f', name: 'Family Pack', price: 699, isAvailable: true },
    ],
    displayOrder: 9,
    popularity: 75,
  },
  {
    id: 'prod-010',
    name: 'Kaju Biriyani',
    slug: 'kaju-biriyani',
    description: 'Rich and creamy biriyani made with premium cashews, fragrant basmati rice, and a delicate blend of spices.',
    shortDescription: 'Rich and creamy biriyani with premium cashews and fragrant rice.',
    category: 'Biriyanis',
    categorySlug: 'biriyanis',
    image: '/images/food/kaju-biriyani.jpg',
    isVeg: true,
    isAvailable: true,
    isFeatured: true,
    variants: [
      { id: 'v-010-s', name: 'Single', price: 249, isAvailable: true },
      { id: 'v-010-f', name: 'Family Pack', price: 699, isAvailable: true },
    ],
    displayOrder: 10,
    popularity: 70,
  },

  // ═══ RICE ITEMS (All 1 KG) ═══
  {
    id: 'prod-011',
    name: 'Pulihora (Tamarind/Lemon)',
    slug: 'pulihora',
    description: 'Traditional tamarind or lemon rice seasoned with peanuts, curry leaves, and tempered spices — a classic Telugu preparation.',
    shortDescription: 'Traditional tamarind/lemon rice with peanuts and tempered spices.',
    category: 'Rice Items',
    categorySlug: 'rice-items',
    image: '/images/food/pulihora.jpg',
    isVeg: true,
    isAvailable: true,
    isFeatured: false,
    variants: [
      { id: 'v-011', name: '1 KG', price: 299, isAvailable: true },
    ],
    servingInfo: '1 KG serves 3-4',
    displayOrder: 1,
    popularity: 65,
  },
  {
    id: 'prod-012',
    name: 'Tomato Rice',
    slug: 'tomato-rice',
    description: 'Tangy and flavourful rice cooked with ripe tomatoes, onions, and aromatic spices for a comforting meal.',
    shortDescription: 'Tangy and flavourful rice cooked with ripe tomatoes and spices.',
    category: 'Rice Items',
    categorySlug: 'rice-items',
    image: '/images/food/tomato-rice.jpg',
    isVeg: true,
    isAvailable: true,
    isFeatured: false,
    variants: [
      { id: 'v-012', name: '1 KG', price: 299, isAvailable: true },
    ],
    servingInfo: '1 KG serves 3-4',
    displayOrder: 2,
    popularity: 60,
  },
  {
    id: 'prod-013',
    name: 'Coconut Rice',
    slug: 'coconut-rice',
    description: 'Fragrant rice tossed with freshly grated coconut, tempered with mustard seeds, curry leaves, and dry chillies.',
    shortDescription: 'Fragrant rice with freshly grated coconut and tempered spices.',
    category: 'Rice Items',
    categorySlug: 'rice-items',
    image: '/images/food/coconut-rice.jpg',
    isVeg: true,
    isAvailable: true,
    isFeatured: false,
    variants: [
      { id: 'v-013', name: '1 KG', price: 299, isAvailable: true },
    ],
    servingInfo: '1 KG serves 3-4',
    displayOrder: 3,
    popularity: 55,
  },
  {
    id: 'prod-014',
    name: 'Pudina Rice',
    slug: 'pudina-rice',
    description: 'Refreshing rice infused with fresh mint leaves, green chillies, and aromatic spices for a unique flavour.',
    shortDescription: 'Refreshing rice with fresh mint and aromatic spices.',
    category: 'Rice Items',
    categorySlug: 'rice-items',
    image: '/images/food/pudina-rice.jpg',
    isVeg: true,
    isAvailable: true,
    isFeatured: false,
    variants: [
      { id: 'v-014', name: '1 KG', price: 299, isAvailable: true },
    ],
    servingInfo: '1 KG serves 3-4',
    displayOrder: 4,
    popularity: 50,
  },
  {
    id: 'prod-015',
    name: 'Sambar Rice',
    slug: 'sambar-rice',
    description: 'Comforting rice mixed with homemade sambar, cooked with lentils and fresh vegetables in traditional spices.',
    shortDescription: 'Comforting rice mixed with homemade sambar and vegetables.',
    category: 'Rice Items',
    categorySlug: 'rice-items',
    image: '/images/food/sambar-rice.jpg',
    isVeg: true,
    isAvailable: true,
    isFeatured: false,
    variants: [
      { id: 'v-015', name: '1 KG', price: 299, isAvailable: true },
    ],
    servingInfo: '1 KG serves 3-4',
    displayOrder: 5,
    popularity: 50,
  },
  {
    id: 'prod-016',
    name: 'Curd Rice',
    slug: 'curd-rice',
    description: 'Cooling and soothing rice mixed with fresh curd, tempered with mustard seeds, curry leaves, and a hint of ginger.',
    shortDescription: 'Cooling curd rice tempered with mustard seeds and curry leaves.',
    category: 'Rice Items',
    categorySlug: 'rice-items',
    image: '/images/food/curd-rice.jpg',
    isVeg: true,
    isAvailable: true,
    isFeatured: false,
    variants: [
      { id: 'v-016', name: '1 KG', price: 299, isAvailable: true },
    ],
    servingInfo: '1 KG serves 3-4',
    displayOrder: 6,
    popularity: 50,
  },

  // ═══ NON-VEG CURRIES ═══
  {
    id: 'prod-017',
    name: 'Chicken Curry',
    slug: 'chicken-curry',
    description: 'Home-style chicken curry simmered with onions, tomatoes, and a blend of traditional spices for a comforting meal.',
    shortDescription: 'Home-style chicken curry with traditional spices.',
    category: 'Non-Veg Curries',
    categorySlug: 'non-veg-curries',
    image: '/images/food/chicken-curry.jpg',
    isVeg: false,
    isAvailable: true,
    isFeatured: false,
    variants: [
      { id: 'v-017-s', name: 'Single', price: 259, isAvailable: true },
      { id: 'v-017-f', name: 'Full', price: 499, isAvailable: true },
    ],
    displayOrder: 1,
    popularity: 80,
  },
  {
    id: 'prod-018',
    name: 'Mutton Curry',
    slug: 'mutton-curry',
    description: 'Rich and flavourful mutton curry slow-cooked with aromatic spices until the meat is tender and succulent.',
    shortDescription: 'Rich mutton curry slow-cooked with aromatic spices.',
    category: 'Non-Veg Curries',
    categorySlug: 'non-veg-curries',
    image: '/images/food/mutton-curry.jpg',
    isVeg: false,
    isAvailable: true,
    isFeatured: false,
    variants: [
      { id: 'v-018-s', name: 'Single', price: 399, isAvailable: true },
      { id: 'v-018-f', name: 'Full', price: 699, isAvailable: true },
    ],
    displayOrder: 2,
    popularity: 75,
  },
  {
    id: 'prod-019',
    name: 'Prawns Curry',
    slug: 'prawns-curry',
    description: 'Fresh prawns cooked in a tangy and spicy curry with coastal spices, creating a delightful seafood experience.',
    shortDescription: 'Fresh prawns in tangy coastal curry.',
    category: 'Non-Veg Curries',
    categorySlug: 'non-veg-curries',
    image: '/images/food/prawns-curry.jpg',
    isVeg: false,
    isAvailable: true,
    isFeatured: false,
    variants: [
      { id: 'v-019-s', name: 'Single', price: 399, isAvailable: true },
      { id: 'v-019-f', name: 'Full', price: 799, isAvailable: true },
    ],
    displayOrder: 3,
    popularity: 70,
  },
  {
    id: 'prod-020',
    name: 'Chicken Fry',
    slug: 'chicken-fry',
    description: 'Crispy and spicy chicken fry prepared with a blend of traditional spices, perfect as a side dish or snack.',
    shortDescription: 'Crispy and spicy chicken fry with traditional spices.',
    category: 'Non-Veg Curries',
    categorySlug: 'non-veg-curries',
    image: '/images/food/chicken-fry.jpg',
    isVeg: false,
    isAvailable: true,
    isFeatured: false,
    variants: [
      { id: 'v-020-s', name: 'Single', price: 229, isAvailable: true },
      { id: 'v-020-f', name: 'Full', price: 459, isAvailable: true },
    ],
    displayOrder: 4,
    popularity: 85,
  },
  {
    id: 'prod-021',
    name: 'Mutton Fry',
    slug: 'mutton-fry',
    description: 'Succulent mutton pieces marinated and fried with aromatic spices for a rich, flavourful experience.',
    shortDescription: 'Succulent mutton pieces fried with aromatic spices.',
    category: 'Non-Veg Curries',
    categorySlug: 'non-veg-curries',
    image: '/images/food/mutton-fry.jpg',
    isVeg: false,
    isAvailable: true,
    isFeatured: false,
    variants: [
      { id: 'v-021-s', name: 'Single', price: 459, isAvailable: true },
      { id: 'v-021-f', name: 'Full', price: 859, isAvailable: true },
    ],
    displayOrder: 5,
    popularity: 70,
  },
  {
    id: 'prod-022',
    name: 'Prawns Fry',
    slug: 'prawns-fry',
    description: 'Fresh prawns marinated in a spicy masala and pan-fried to golden perfection with coastal flavours.',
    shortDescription: 'Fresh prawns marinated and fried with coastal masala.',
    category: 'Non-Veg Curries',
    categorySlug: 'non-veg-curries',
    image: '/images/food/prawns-fry.jpg',
    isVeg: false,
    isAvailable: true,
    isFeatured: false,
    variants: [
      { id: 'v-022-s', name: 'Single', price: 459, isAvailable: true },
      { id: 'v-022-f', name: 'Full', price: 959, isAvailable: true },
    ],
    displayOrder: 6,
    popularity: 65,
  },

  // ═══ VEG CURRIES ═══
  {
    id: 'prod-023',
    name: 'Paneer Curry',
    slug: 'paneer-curry',
    description: 'Soft paneer cubes simmered in a rich, creamy gravy with tomatoes, onions, and a blend of aromatic spices.',
    shortDescription: 'Soft paneer in rich, creamy gravy with aromatic spices.',
    category: 'Veg Curries',
    categorySlug: 'veg-curries',
    image: '/images/food/paneer-curry.jpg',
    isVeg: true,
    isAvailable: true,
    isFeatured: false,
    variants: [
      { id: 'v-023-s', name: 'Single', price: 199, isAvailable: true },
      { id: 'v-023-f', name: 'Full', price: 399, isAvailable: true },
    ],
    displayOrder: 1,
    popularity: 70,
  },
  {
    id: 'prod-024',
    name: 'Guthi Vankay',
    slug: 'guthi-vankay',
    description: 'Stuffed baby brinjals cooked in a tangy peanut and sesame gravy — a classic Andhra delicacy.',
    shortDescription: 'Stuffed baby brinjals in tangy peanut-sesame gravy.',
    category: 'Veg Curries',
    categorySlug: 'veg-curries',
    image: '/images/food/guthi-vankay.jpg',
    isVeg: true,
    isAvailable: true,
    isFeatured: false,
    variants: [
      { id: 'v-024-s', name: 'Single', price: 149, isAvailable: true },
      { id: 'v-024-f', name: 'Full', price: 299, isAvailable: true },
    ],
    displayOrder: 2,
    popularity: 55,
  },
  {
    id: 'prod-025',
    name: 'Sambar',
    slug: 'sambar',
    description: 'Traditional lentil stew with mixed vegetables, tamarind, and a fragrant spice blend — a South Indian staple.',
    shortDescription: 'Traditional lentil stew with mixed vegetables and tamarind.',
    category: 'Veg Curries',
    categorySlug: 'veg-curries',
    image: '/images/food/sambar.jpg',
    isVeg: true,
    isAvailable: true,
    isFeatured: false,
    variants: [
      { id: 'v-025-s', name: 'Single', price: 49, isAvailable: true },
      { id: 'v-025-f', name: 'Full', price: 159, isAvailable: true },
    ],
    displayOrder: 3,
    popularity: 60,
  },
  {
    id: 'prod-026',
    name: 'Rasam',
    slug: 'rasam',
    description: 'A soothing, tangy soup made with tamarind, tomatoes, pepper, and aromatic herbs — perfect for warmth and comfort.',
    shortDescription: 'Soothing tangy soup with tamarind, tomatoes, and pepper.',
    category: 'Veg Curries',
    categorySlug: 'veg-curries',
    image: '/images/food/rasam.jpg',
    isVeg: true,
    isAvailable: true,
    isFeatured: false,
    variants: [
      { id: 'v-026-s', name: 'Single', price: 49, isAvailable: true },
      { id: 'v-026-f', name: 'Full', price: 99, isAvailable: true },
    ],
    displayOrder: 4,
    popularity: 50,
  },
  {
    id: 'prod-027',
    name: 'Roti Pachadi',
    slug: 'roti-pachadi',
    description: 'A refreshing chutney made with fresh beetroot, onions, and spices — a traditional Andhra accompaniment.',
    shortDescription: 'Refreshing beetroot chutney with onions and spices.',
    category: 'Veg Curries',
    categorySlug: 'veg-curries',
    image: '/images/food/roti-pachadi.jpg',
    isVeg: true,
    isAvailable: true,
    isFeatured: false,
    variants: [
      { id: 'v-027-s', name: 'Single', price: 59, isAvailable: true },
      { id: 'v-027-f', name: 'Full', price: 119, isAvailable: true },
    ],
    displayOrder: 5,
    popularity: 40,
  },
  {
    id: 'prod-028',
    name: 'Veg Curries (Choice)',
    slug: 'veg-curries-choice',
    description: 'Choose from our selection of daily vegetable curries, prepared with fresh seasonal vegetables and traditional spices.',
    shortDescription: 'Daily vegetable curry of your choice with traditional spices.',
    category: 'Veg Curries',
    categorySlug: 'veg-curries',
    image: '/images/food/veg-curries-choice.jpg',
    isVeg: true,
    isAvailable: true,
    isFeatured: false,
    variants: [
      { id: 'v-028-s', name: 'Single', price: 99, isAvailable: true },
      { id: 'v-028-f', name: 'Full', price: 129, isAvailable: true },
    ],
    displayOrder: 6,
    popularity: 45,
  },
  {
    id: 'prod-029',
    name: 'Veg Fry (Choice)',
    slug: 'veg-fry-choice',
    description: 'Choose from our selection of daily vegetable fries — crispy, flavourful, and made with fresh seasonal vegetables.',
    shortDescription: 'Daily vegetable fry of your choice, crispy and flavourful.',
    category: 'Veg Curries',
    categorySlug: 'veg-curries',
    image: '/images/food/veg-fry-choice.jpg',
    isVeg: true,
    isAvailable: true,
    isFeatured: false,
    variants: [
      { id: 'v-029-s', name: 'Single', price: 119, isAvailable: true },
      { id: 'v-029-f', name: 'Full', price: 199, isAvailable: true },
    ],
    displayOrder: 7,
    popularity: 45,
  },

  // ═══ SWEETS (All 1 KG) ═══
  {
    id: 'prod-030',
    name: 'Semiya Kesari',
    slug: 'semiya-kesari',
    description: 'Delicate vermicelli cooked with ghee, sugar, and aromatic cardamom, garnished with cashews and raisins.',
    shortDescription: 'Delicate vermicelli with ghee, cardamom, cashews, and raisins.',
    category: 'Sweets',
    categorySlug: 'sweets',
    image: '/images/food/semiya-kesari.jpg',
    isVeg: true,
    isAvailable: true,
    isFeatured: false,
    variants: [
      { id: 'v-030', name: '1 KG', price: 459, isAvailable: true },
    ],
    servingInfo: '1 KG',
    displayOrder: 1,
    popularity: 55,
  },
  {
    id: 'prod-031',
    name: 'Rava Kesari',
    slug: 'rava-kesari',
    description: 'Rich semolina pudding infused with saffron and cardamom, made with pure ghee and garnished with dry fruits.',
    shortDescription: 'Rich semolina pudding with saffron, cardamom, and ghee.',
    category: 'Sweets',
    categorySlug: 'sweets',
    image: '/images/food/rava-kesari.jpg',
    isVeg: true,
    isAvailable: true,
    isFeatured: false,
    variants: [
      { id: 'v-031', name: '1 KG', price: 499, isAvailable: true },
    ],
    servingInfo: '1 KG',
    displayOrder: 2,
    popularity: 55,
  },
  {
    id: 'prod-032',
    name: 'Semiya-Saggubiyyam Kheer',
    slug: 'semiya-saggubiyyam-kheer',
    description: 'Creamy milk-based dessert with vermicelli and sago pearls, sweetened with sugar and scented with cardamom.',
    shortDescription: 'Creamy milk dessert with vermicelli, sago, and cardamom.',
    category: 'Sweets',
    categorySlug: 'sweets',
    image: '/images/food/semiya-saggubiyyam-kheer.jpg',
    isVeg: true,
    isAvailable: true,
    isFeatured: false,
    variants: [
      { id: 'v-032', name: '1 KG', price: 499, isAvailable: true },
    ],
    servingInfo: '1 KG',
    displayOrder: 3,
    popularity: 50,
  },
  {
    id: 'prod-033',
    name: 'Bread Halwa',
    slug: 'bread-halwa',
    description: 'A unique and rich sweet made by deep-frying bread slices in ghee, mixed with sugar syrup, cardamom, and nuts.',
    shortDescription: 'Rich bread-based sweet with ghee, sugar syrup, and nuts.',
    category: 'Sweets',
    categorySlug: 'sweets',
    image: '/images/food/bread-halwa.jpg',
    isVeg: true,
    isAvailable: true,
    isFeatured: false,
    variants: [
      { id: 'v-033', name: '1 KG', price: 599, isAvailable: true },
    ],
    servingInfo: '1 KG',
    displayOrder: 4,
    popularity: 50,
  },
  {
    id: 'prod-034',
    name: 'Kadhuka Kheer',
    slug: 'kadhuka-kheer',
    description: 'A festive milk-based dessert made with dates and dry fruits, simmered to a creamy, rich consistency.',
    shortDescription: 'Festive milk dessert with dates and dry fruits.',
    category: 'Sweets',
    categorySlug: 'sweets',
    image: '/images/food/kadhuka-kheer.jpg',
    isVeg: true,
    isAvailable: true,
    isFeatured: false,
    variants: [
      { id: 'v-034', name: '1 KG', price: 599, isAvailable: true },
    ],
    servingInfo: '1 KG',
    displayOrder: 5,
    popularity: 45,
  },
  {
    id: 'prod-035',
    name: 'Carrot Halwa',
    slug: 'carrot-halwa',
    description: 'Freshly grated carrots slow-cooked in milk and ghee, sweetened with sugar and garnished with nuts.',
    shortDescription: 'Fresh carrots slow-cooked in milk, ghee, and nuts.',
    category: 'Sweets',
    categorySlug: 'sweets',
    image: '/images/food/carrot-halwa.jpg',
    isVeg: true,
    isAvailable: true,
    isFeatured: false,
    variants: [
      { id: 'v-035', name: '1 KG', price: 699, isAvailable: true },
    ],
    servingInfo: '1 KG',
    displayOrder: 6,
    popularity: 60,
  },
  {
    id: 'prod-036',
    name: 'Sheer Kurma',
    slug: 'sheer-kurma',
    description: 'A luxurious vermicelli pudding made with whole milk, dates, dry fruits, and delicate spices — a festive favourite.',
    shortDescription: 'Luxurious vermicelli pudding with dates and dry fruits.',
    category: 'Sweets',
    categorySlug: 'sweets',
    image: '/images/food/sheer-kurma.jpg',
    isVeg: true,
    isAvailable: true,
    isFeatured: false,
    variants: [
      { id: 'v-036', name: '1 KG', price: 699, isAvailable: true },
    ],
    servingInfo: '1 KG',
    displayOrder: 7,
    popularity: 55,
  },
  {
    id: 'prod-037',
    name: 'Pala Thalikalu',
    slug: 'pala-thalikalu',
    description: 'Traditional Andhra sweet made with rice flour dumplings simmered in sweetened milk, cardamom, and dry fruits.',
    shortDescription: 'Rice flour dumplings in sweetened milk with cardamom.',
    category: 'Sweets',
    categorySlug: 'sweets',
    image: '/images/food/pala-thalikalu.jpg',
    isVeg: true,
    isAvailable: true,
    isFeatured: false,
    variants: [
      { id: 'v-037', name: '1 KG', price: 699, isAvailable: true },
    ],
    servingInfo: '1 KG',
    displayOrder: 8,
    popularity: 45,
  },

  // ═══ SNACKS — SWEET (All 1 KG) ═══
  {
    id: 'prod-038',
    name: 'Boondhi Laddu',
    slug: 'boondhi-laddu',
    description: 'Golden besan boondi balls sweetened with sugar syrup, infused with cardamom, and garnished with cashews.',
    shortDescription: 'Golden besan boondi balls with sugar syrup and cardamom.',
    category: 'Snacks — Sweet',
    categorySlug: 'snacks-sweet',
    image: '/images/food/boondhi-laddu.jpg',
    isVeg: true,
    isAvailable: true,
    isFeatured: false,
    variants: [
      { id: 'v-038', name: '1 KG', price: 599, isAvailable: true },
    ],
    servingInfo: '1 KG',
    displayOrder: 1,
    popularity: 60,
  },
  {
    id: 'prod-039',
    name: 'Ravva Laddu',
    slug: 'ravva-laddu',
    description: 'Semolina laddus made with roasted rava, ghee, sugar, and garnished with cashews and cardamom.',
    shortDescription: 'Roasted semolina laddus with ghee, sugar, and cashews.',
    category: 'Snacks — Sweet',
    categorySlug: 'snacks-sweet',
    image: '/images/food/ravva-laddu.jpg',
    isVeg: true,
    isAvailable: true,
    isFeatured: false,
    variants: [
      { id: 'v-039', name: '1 KG', price: 499, isAvailable: true },
    ],
    servingInfo: '1 KG',
    displayOrder: 2,
    popularity: 55,
  },
  {
    id: 'prod-040',
    name: 'Sunnundalu (Jaggery)',
    slug: 'sunnundalu-jaggery',
    description: 'Traditional urad dal laddus sweetened with jaggery and flavoured with cardamom — a nutritious festive treat.',
    shortDescription: 'Traditional urad dal laddus with jaggery and cardamom.',
    category: 'Snacks — Sweet',
    categorySlug: 'snacks-sweet',
    image: '/images/food/sunnundalu-jaggery.jpg',
    isVeg: true,
    isAvailable: true,
    isFeatured: false,
    variants: [
      { id: 'v-040', name: '1 KG', price: 799, isAvailable: true },
    ],
    servingInfo: '1 KG',
    displayOrder: 3,
    popularity: 50,
  },
  {
    id: 'prod-041',
    name: 'Sunnundalu (Sugar)',
    slug: 'sunnundalu-sugar',
    description: 'Traditional urad dal laddus made with powdered sugar and ghee — a lighter variation of the classic sweet.',
    shortDescription: 'Traditional urad dal laddus with powdered sugar and ghee.',
    category: 'Snacks — Sweet',
    categorySlug: 'snacks-sweet',
    image: '/images/food/sunnundalu-sugar.jpg',
    isVeg: true,
    isAvailable: true,
    isFeatured: false,
    variants: [
      { id: 'v-041', name: '1 KG', price: 729, isAvailable: true },
    ],
    servingInfo: '1 KG',
    displayOrder: 4,
    popularity: 45,
  },
  {
    id: 'prod-042',
    name: 'Kobbari Laddu',
    slug: 'kobbari-laddu',
    description: 'Sweet coconut laddus made with freshly grated coconut, sugar, and a hint of cardamom.',
    shortDescription: 'Sweet coconut laddus with fresh coconut and cardamom.',
    category: 'Snacks — Sweet',
    categorySlug: 'snacks-sweet',
    image: '/images/food/kobbari-laddu.jpg',
    isVeg: true,
    isAvailable: true,
    isFeatured: false,
    variants: [
      { id: 'v-042', name: '1 KG', price: 569, isAvailable: true },
    ],
    servingInfo: '1 KG',
    displayOrder: 5,
    popularity: 50,
  },
  {
    id: 'prod-043',
    name: 'Dry Fruits Laddu',
    slug: 'dry-fruits-laddu',
    description: 'Premium laddus made with a rich blend of dry fruits, nuts, and ghee — a luxurious and nutritious sweet.',
    shortDescription: 'Premium laddus with rich dry fruits, nuts, and ghee.',
    category: 'Snacks — Sweet',
    categorySlug: 'snacks-sweet',
    image: '/images/food/dry-fruits-laddu.jpg',
    isVeg: true,
    isAvailable: true,
    isFeatured: false,
    variants: [
      { id: 'v-043', name: '1 KG', price: 799, isAvailable: true },
    ],
    servingInfo: '1 KG',
    displayOrder: 6,
    popularity: 55,
  },
  {
    id: 'prod-044',
    name: 'Sajja Burelu',
    slug: 'sajja-burelu',
    description: 'Traditional Andhra sweet made with pearl millet flour, stuffed with coconut and jaggery filling.',
    shortDescription: 'Pearl millet sweet stuffed with coconut and jaggery.',
    category: 'Snacks — Sweet',
    categorySlug: 'snacks-sweet',
    image: '/images/food/sajja-burelu.jpg',
    isVeg: true,
    isAvailable: true,
    isFeatured: false,
    variants: [
      { id: 'v-044', name: '1 KG', price: 499, isAvailable: true },
    ],
    servingInfo: '1 KG',
    displayOrder: 7,
    popularity: 40,
  },
  {
    id: 'prod-045',
    name: 'Bellam Ariselu',
    slug: 'bellam-ariselu',
    description: 'Traditional Telugu festive sweet made with rice flour and jaggery, deep-fried to golden perfection.',
    shortDescription: 'Festive rice flour and jaggery sweet, deep-fried golden.',
    category: 'Snacks — Sweet',
    categorySlug: 'snacks-sweet',
    image: '/images/food/bellam-ariselu.jpg',
    isVeg: true,
    isAvailable: true,
    isFeatured: false,
    variants: [
      { id: 'v-045', name: '1 KG', price: 499, isAvailable: true },
    ],
    servingInfo: '1 KG',
    displayOrder: 8,
    popularity: 45,
  },
  {
    id: 'prod-046',
    name: 'Kobbari Burelu',
    slug: 'kobbari-burelu',
    description: 'Sweet rice flour parcels stuffed with a fragrant coconut and jaggery mixture — a traditional Andhra delight.',
    shortDescription: 'Rice flour parcels with coconut and jaggery filling.',
    category: 'Snacks — Sweet',
    categorySlug: 'snacks-sweet',
    image: '/images/food/kobbari-burelu.jpg',
    isVeg: true,
    isAvailable: true,
    isFeatured: false,
    variants: [
      { id: 'v-046', name: '1 KG', price: 499, isAvailable: true },
    ],
    servingInfo: '1 KG',
    displayOrder: 9,
    popularity: 40,
  },

  // ═══ SNACKS — HOT (All 1 KG) ═══
  {
    id: 'prod-047',
    name: 'Karappusa / Chakralu / Murukulu',
    slug: 'karappusa-chakralu-murukulu',
    description: 'Crunchy rice flour spirals and twisted shapes, deep-fried to crispy perfection with sesame seeds and cumin.',
    shortDescription: 'Crunchy rice flour spirals with sesame and cumin.',
    category: 'Snacks — Hot',
    categorySlug: 'snacks-hot',
    image: '/images/food/karappusa.jpg',
    isVeg: true,
    isAvailable: true,
    isFeatured: false,
    variants: [
      { id: 'v-047', name: '1 KG', price: 399, isAvailable: true },
    ],
    servingInfo: '1 KG',
    displayOrder: 1,
    popularity: 55,
  },
  {
    id: 'prod-048',
    name: 'Chakkalu',
    slug: 'chakkalu',
    description: 'Traditional savoury rice flour crackers seasoned with cumin and sesame — a crunchy Telugu snack favourite.',
    shortDescription: 'Traditional rice flour crackers with cumin and sesame.',
    category: 'Snacks — Hot',
    categorySlug: 'snacks-hot',
    image: '/images/food/chakkalu.jpg',
    isVeg: true,
    isAvailable: true,
    isFeatured: false,
    variants: [
      { id: 'v-048', name: '1 KG', price: 399, isAvailable: true },
    ],
    servingInfo: '1 KG',
    displayOrder: 2,
    popularity: 50,
  },
  {
    id: 'prod-049',
    name: 'Sanna Karappusa',
    slug: 'sanna-karappusa',
    description: 'Fine and delicate rice flour crisps, lighter and thinner than regular karappusa, with a satisfying crunch.',
    shortDescription: 'Fine and delicate rice flour crisps, light and crispy.',
    category: 'Snacks — Hot',
    categorySlug: 'snacks-hot',
    image: '/images/food/sanna-karappusa.jpg',
    isVeg: true,
    isAvailable: true,
    isFeatured: false,
    variants: [
      { id: 'v-049', name: '1 KG', price: 599, isAvailable: true },
    ],
    servingInfo: '1 KG',
    displayOrder: 3,
    popularity: 45,
  },
  {
    id: 'prod-050',
    name: 'Chekodilu',
    slug: 'chekodilu',
    description: 'Traditional ring-shaped rice flour snack, deep-fried and mildly spiced — a beloved Andhra teatime snack.',
    shortDescription: 'Ring-shaped rice flour snack, crispy and mildly spiced.',
    category: 'Snacks — Hot',
    categorySlug: 'snacks-hot',
    image: '/images/food/chekodilu.jpg',
    isVeg: true,
    isAvailable: true,
    isFeatured: false,
    variants: [
      { id: 'v-050', name: '1 KG', price: 359, isAvailable: true },
    ],
    servingInfo: '1 KG',
    displayOrder: 4,
    popularity: 45,
  },
  {
    id: 'prod-051',
    name: 'Boondhi Mixture',
    slug: 'boondhi-mixture',
    description: 'Crunchy besan boondi mixed with peanuts, curry leaves, and spices — a perfect all-occasion savoury snack.',
    shortDescription: 'Crunchy boondi with peanuts, curry leaves, and spices.',
    category: 'Snacks — Hot',
    categorySlug: 'snacks-hot',
    image: '/images/food/boondhi-mixture.jpg',
    isVeg: true,
    isAvailable: true,
    isFeatured: false,
    variants: [
      { id: 'v-051', name: '1 KG', price: 399, isAvailable: true },
    ],
    servingInfo: '1 KG',
    displayOrder: 5,
    popularity: 55,
  },
  {
    id: 'prod-052',
    name: 'Jonna Atukula Mixture',
    slug: 'jonna-atukula-mixture',
    description: 'Sorghum flakes mixed with peanuts, curry leaves, and spices — a nutritious and crunchy traditional snack.',
    shortDescription: 'Sorghum flakes with peanuts, curry leaves, and spices.',
    category: 'Snacks — Hot',
    categorySlug: 'snacks-hot',
    image: '/images/food/jonna-atukula-mixture.jpg',
    isVeg: true,
    isAvailable: true,
    isFeatured: false,
    variants: [
      { id: 'v-052', name: '1 KG', price: 399, isAvailable: true },
    ],
    servingInfo: '1 KG',
    displayOrder: 6,
    popularity: 45,
  },
  {
    id: 'prod-053',
    name: 'Onion Pakodi',
    slug: 'onion-pakodi',
    description: 'Crispy onion fritters made with besan batter and spices — a classic tea-time favourite, served hot and crunchy.',
    shortDescription: 'Crispy onion fritters with besan and spices.',
    category: 'Snacks — Hot',
    categorySlug: 'snacks-hot',
    image: '/images/food/onion-pakodi.jpg',
    isVeg: true,
    isAvailable: true,
    isFeatured: false,
    variants: [
      { id: 'v-053', name: '1 KG', price: 259, isAvailable: true },
    ],
    servingInfo: '1 KG',
    displayOrder: 7,
    popularity: 60,
  },
];

// ── Navigation Links ──
export const NAV_LINKS = [
  { label: 'Home', href: '/' },
  { label: 'Menu', href: '/menu' },
  { label: 'About', href: '/about' },
  { label: 'Offers', href: '/offers' },
  { label: 'Contact', href: '/contact' },
] as const;

export const FOOTER_LINKS = {
  quickLinks: [
    { label: 'Home', href: '/' },
    { label: 'Menu', href: '/menu' },
    { label: 'About', href: '/about' },
    { label: 'Contact', href: '/contact' },
    { label: 'Offers', href: '/offers' },
    { label: 'FAQ', href: '/faq' },
  ],
  legal: [
    { label: 'Privacy Policy', href: '/privacy' },
    { label: 'Terms & Conditions', href: '/terms' },
    { label: 'Refund Policy', href: '/refund-policy' },
  ],
} as const;

// ── Order Status Labels ──
export const ORDER_STATUS_LABELS: Record<string, string> = {
  placed: 'Order Placed',
  payment_pending: 'Payment Pending',
  payment_confirmed: 'Payment Confirmed',
  payment_failed: 'Payment Failed',
  accepted: 'Order Accepted',
  preparing: 'Preparing',
  ready: 'Ready',
  out_for_delivery: 'Out for Delivery',
  delivered: 'Delivered',
  cancelled: 'Cancelled',
  refund_pending: 'Refund Pending',
  refunded: 'Refunded',
};


// ── Business Hours Default ──
export const DEFAULT_BUSINESS_HOURS = [
  { day: 'Monday', isOpen: true, openTime: '11:00', closeTime: '22:00' },
  { day: 'Tuesday', isOpen: true, openTime: '11:00', closeTime: '22:00' },
  { day: 'Wednesday', isOpen: true, openTime: '11:00', closeTime: '22:00' },
  { day: 'Thursday', isOpen: true, openTime: '11:00', closeTime: '22:00' },
  { day: 'Friday', isOpen: true, openTime: '11:00', closeTime: '22:00' },
  { day: 'Saturday', isOpen: true, openTime: '11:00', closeTime: '22:00' },
  { day: 'Sunday', isOpen: true, openTime: '11:00', closeTime: '22:00' },
];
